export interface AnalyticsEvent {
    id?: string;
    user_id?: string | null;
    event_type: string;
    occurred_at?: string;
    path?: string | null;
    referer?: string | null;
    referrer_host?: string | null;
    device_type?: string | null;
    language?: string | null;
    country?: string | null;
    country_code?: string | null;
    region?: string | null;
    city?: string | null;
    page_title?: string | null;
    action_name?: string | null;
    action_target?: string | null;
    session_id?: string | null;
    visitor_id?: string | null;
    consent_status?: "granted" | "denied" | "unknown" | null;
    privacy_mode?: "consented" | "opted_out" | "gpc" | "dnt" | "unknown" | null;
    gpc_signal?: boolean;
    dnt_signal?: boolean;
    is_bot?: boolean;
    user_agent_hash?: string | null;
    ip_hash?: string | null;
    utm_source?: string | null;
    utm_medium?: string | null;
    utm_campaign?: string | null;
    utm_term?: string | null;
    utm_content?: string | null;
    metadata?: Record<string, unknown> | null;
    created_at?: string;
}
